### PR TITLE
Remove modification/usage of default JsonSerializerSettings

### LINKED ISSUE #242: KubeOps changes default JSON serialization settings
**Describe the bug**
KubeOps changes default JSON serialization settings. This might influence other components that use the default JSON serialization settings. 

**To Reproduce**
Use a JSON serializer with the default serialization settings in a KubeOps operator and outside, e.g., in a unit test.

**Expected behavior**
The serialized output should be identical (or at least when disregarding line breaks and spacing).

**Additional context**
The way field names are cased by the JSON serialization settings configured by KubeOps also seems to be problematic in general. Here are some examples for field names serialized without and with the KubeOps settings:

- client_app_id -> clienT_APP_ID
- account_name -> accounT_NAME
- session_paramenters -> sessioN_PARAMETERS

In fact, this prevents us from connecting to Snowflake using the Snowflake connector as described in #241, as running the Snowflake connector in a KubeOps operator changes the casing of the fields in its requests.

### PR DESCRIPTION
**Pull request by erin-allison**
The library really shouldn't rely upon or modify the default JsonSerializerSettings since other libraries could conflict, user code could muck with it, etc.

This fixes #242

### CODE REVIEW

File: src/KubeOps/Operator/OperatorSettings.cs [hunk 1]
```diff
@@ -78,5 +79,7 @@ public sealed class OperatorSettings
         /// <para>The search will be performed on each "Start" of the controller.</para>
         /// </summary>
         public bool PreloadCache { get; set; }
+
+        internal JsonSerializerSettings SerializerSettings { get; set; } = null!;
```
Comment (buehler) [inline src/KubeOps/Operator/OperatorSettings.cs:83]: instead of setting this to `null!` (which is just my personal opinion), would it suffice to add the JsonSerializerSettings as singleton to the dependency injection and then just inject the settings when needed?

File: src/KubeOps/Operator/Builder/OperatorBuilder.cs [hunk 2]
```diff
@@ -123,8 +121,8 @@ internal IOperatorBuilder AddOperatorBase(OperatorSettings settings)
                 },
                 DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.ffffffK",
             };
-            Services.AddTransient(_ => jsonSettings);
-            JsonConvert.DefaultSettings = () => jsonSettings;
+
+            Services.AddSingleton(settings);
```
Comment (buehler) [inline src/KubeOps/Operator/Builder/OperatorBuilder.cs:125]: correlates with the comment below.
```suggestion
            Services.AddSingleton(settings);
            Services.AddSingleton(new JsonSerializerSettings { ... });
```

and then inject the settings when needed (instead of operator settings and set a particular field to `null!`)

File: src/KubeOps/Operator/Serialization/EntitySerializer.cs [hunk 3]
```diff
@@ -9,10 +9,10 @@ internal class EntitySerializer
         private readonly ISerializer _yaml;
         private readonly JsonSerializerSettings _jsonSettings;
 
-        public EntitySerializer(ISerializer yaml, JsonSerializerSettings jsonSettings)
+        public EntitySerializer(ISerializer yaml, OperatorSettings operatorSettings)
```
Comment (buehler) [inline src/KubeOps/Operator/Serialization/EntitySerializer.cs:12]: here we could inject the settings and use them accordingly
```suggestion
        public EntitySerializer(ISerializer yaml, JsonSerializerSettings serializerSettings)
```

File: src/KubeOps/Operator/Serialization/EntitySerializer.cs [hunk 4]
```diff
@@ -9,10 +9,10 @@ internal class EntitySerializer
...
         {
             _yaml = yaml;
-            _jsonSettings = jsonSettings;
+            _jsonSettings = operatorSettings.SerializerSettings;
```
Comment (buehler) [inline src/KubeOps/Operator/Serialization/EntitySerializer.cs:15]:
```suggestion
            _jsonSettings = serializerSettings;
```

**Review by buehler — CHANGES_REQUESTED** [review]
What do you think about those proposals?
In general I'm a fan of "not overpowering" compiler help (in this example the usage of `null!`). That's why I suggest to use the JsonSerializerSettings as injectable singleton (without changing the default settings)

**Comment by erin-allison** [comment]
I'm not a crazy fan of adding something that generic into the DI container; it is just one more place where someone could very inadvertently override settings that _need_ to be set for the library to function properly.

How about this instead? Moving the default value into `OperatorSettings` gets rid of the nullable override. This will also make it easy to expose that property if there is a desire in the future to allow customization of the serialization options (i.e. adding converters for custom CLR types).

**Comment by erin-allison** [comment]
Rebased to master

**Review by buehler — APPROVED** [review]
That is definitely a good way to go.
